import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import { twMerge } from "tailwind-merge";
import Navigation from "@/ui/organisms/Navigation/Navigation";
import "./globals.css";
import Footer from "@/ui/organisms/Footer/Footer";

export const openSans = Open_Sans({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-opensans",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={twMerge("light", openSans.variable)}>
			<body className={twMerge("bg-bg text-custom-text-color")}>
				<Navigation />
				<main className="mx-auto flex min-h-screen max-w-[1280px] flex-col items-center justify-between">
					{children}
				</main>
				<Footer />
			</body>
		</html>
	);
}
